# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-12-10 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clickevent',
            old_name='counts',
            new_name='count',
        ),
        migrations.RenameField(
            model_name='clickevent',
            old_name='fes_url',
            new_name='kirr_url',
        ),
        migrations.AddField(
            model_name='clickevent',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
